name: poc-ozerus

services:
  ds:
    build:
      context: .
      dockerfile: Dockerfile.ds
    networks: [default, web]
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - NODE_ENV=production
      - PORT=4000
    networks: [default]
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - NODE_ENV=production
      - PORT=3001
      - API_PROXY_URL=http://api:4000
      - GATE_USER=${GATE_USER:-acelys}
      - GATE_PASS=${GATE_PASS:-Kp9#mVx2-tR7nQ4wL8bH}
    depends_on:
      - api
    networks: [default, web]
    restart: unless-stopped

networks:
  web:
    external: true