/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { OzAvatarTone } from "./components/oz-avatar/oz-avatar";
import { OzButtonSize, OzButtonVariant } from "./components/oz-button/oz-button";
import { OzCardBorder, OzCardPadding, OzCardTone } from "./components/oz-card/oz-card";
import { OzIconName } from "./components/oz-icon/oz-icon";
import { OzTagTone } from "./components/oz-tag/oz-tag";
import { OzIconName as OzIconName1 } from "./components/oz-icon/oz-icon";
import { OzInputSize } from "./components/oz-input/oz-input";
import { OzSeries } from "./components/oz-line-chart/oz-line-chart";
import { OzProductRow } from "./components/oz-product-table/oz-product-table";
import { OzTagTone as OzTagTone1, OzTagVariant } from "./components/oz-tag/oz-tag";
export { OzAvatarTone } from "./components/oz-avatar/oz-avatar";
export { OzButtonSize, OzButtonVariant } from "./components/oz-button/oz-button";
export { OzCardBorder, OzCardPadding, OzCardTone } from "./components/oz-card/oz-card";
export { OzIconName } from "./components/oz-icon/oz-icon";
export { OzTagTone } from "./components/oz-tag/oz-tag";
export { OzIconName as OzIconName1 } from "./components/oz-icon/oz-icon";
export { OzInputSize } from "./components/oz-input/oz-input";
export { OzSeries } from "./components/oz-line-chart/oz-line-chart";
export { OzProductRow } from "./components/oz-product-table/oz-product-table";
export { OzTagTone as OzTagTone1, OzTagVariant } from "./components/oz-tag/oz-tag";
export namespace Components {
    interface OzAvatar {
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default 32
         */
        "size": number;
        /**
          * @default 'forest'
         */
        "tone": OzAvatarTone;
    }
    interface OzButton {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 'md'
         */
        "size": OzButtonSize;
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * @default 'primary'
         */
        "variant": OzButtonVariant;
    }
    interface OzCard {
        /**
          * @default 'solid'
         */
        "border": OzCardBorder;
        /**
          * @default false
         */
        "elevated": boolean;
        "heading"?: string;
        /**
          * @default false
         */
        "interactive": boolean;
        /**
          * @default 'md'
         */
        "padding": OzCardPadding;
        "subheading"?: string;
        /**
          * @default 'default'
         */
        "tone": OzCardTone;
    }
    interface OzEmptyState {
        "body"?: string;
        /**
          * @default ''
         */
        "heading": string;
        /**
          * @default 'doc'
         */
        "icon": OzIconName;
    }
    interface OzEventRow {
        /**
          * @default ''
         */
        "amount": string;
        /**
          * @default ''
         */
        "dateDay": string;
        /**
          * @default ''
         */
        "dateMonth": string;
        /**
          * @default ''
         */
        "kind": string;
        /**
          * @default ''
         */
        "product": string;
        /**
          * @default 'forest'
         */
        "tone": OzTagTone;
    }
    interface OzHeader {
        /**
          * @default 'Tableau de bord'
         */
        "heading": string;
        /**
          * @default 3
         */
        "notificationCount": number;
        /**
          * @default 'Rechercher un ISIN, produit, client…'
         */
        "searchPlaceholder": string;
    }
    interface OzIcon {
        /**
          * @default 'currentColor'
         */
        "color": string;
        /**
          * @default 'dashboard'
         */
        "name": OzIconName1;
        /**
          * @default 16
         */
        "size": number;
        /**
          * @default 1.6
         */
        "strokeWidth": number;
    }
    interface OzInput {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "error": boolean;
        "hint"?: string;
        "label"?: string;
        "placeholder"?: string;
        /**
          * @default 'md'
         */
        "size": OzInputSize;
        /**
          * @default 'text'
         */
        "type": string;
        /**
          * @default ''
         */
        "value": string;
    }
    interface OzKpi {
        "delta"?: string;
        /**
          * @default 'success'
         */
        "deltaTone": OzTagTone;
        /**
          * @default ''
         */
        "label": string;
        "sub"?: string;
        "unit"?: string;
        /**
          * @default ''
         */
        "value": string;
    }
    interface OzLineChart {
        /**
          * @default 220
         */
        "h": number;
        /**
          * @default []
         */
        "series": OzSeries[] | string;
        /**
          * @default 560
         */
        "w": number;
        /**
          * @default []
         */
        "yLabels": string[] | string;
    }
    interface OzProductTable {
        /**
          * @default false
         */
        "compact": boolean;
        /**
          * @default DEFAULT_ROWS
         */
        "rows": OzProductRow[] | string;
    }
    interface OzSidebar {
        /**
          * @default 'dashboard'
         */
        "active": string;
        /**
          * @default 'Cabinet Helios'
         */
        "org": string;
        /**
          * @default 'Marie Laurent'
         */
        "user": string;
    }
    interface OzSparkline {
        /**
          * @default 'var(--oz-forest)'
         */
        "color": string;
        /**
          * @default []
         */
        "data": number[] | string;
        /**
          * @default 36
         */
        "h": number;
        /**
          * @default 160
         */
        "w": number;
    }
    interface OzSwatch {
        /**
          * @default 'var(--oz-ink)'
         */
        "fg": string;
        /**
          * @default 84
         */
        "h": number;
        "label"?: string;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default ''
         */
        "value": string;
        /**
          * @default 132
         */
        "w": number;
    }
    interface OzTag {
        /**
          * @default 'neutral'
         */
        "tone": OzTagTone1;
        /**
          * @default 'soft'
         */
        "variant": OzTagVariant;
    }
}
export interface OzInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOzInputElement;
}
declare global {
    interface HTMLOzAvatarElement extends Components.OzAvatar, HTMLStencilElement {
    }
    var HTMLOzAvatarElement: {
        prototype: HTMLOzAvatarElement;
        new (): HTMLOzAvatarElement;
    };
    interface HTMLOzButtonElement extends Components.OzButton, HTMLStencilElement {
    }
    var HTMLOzButtonElement: {
        prototype: HTMLOzButtonElement;
        new (): HTMLOzButtonElement;
    };
    interface HTMLOzCardElement extends Components.OzCard, HTMLStencilElement {
    }
    var HTMLOzCardElement: {
        prototype: HTMLOzCardElement;
        new (): HTMLOzCardElement;
    };
    interface HTMLOzEmptyStateElement extends Components.OzEmptyState, HTMLStencilElement {
    }
    var HTMLOzEmptyStateElement: {
        prototype: HTMLOzEmptyStateElement;
        new (): HTMLOzEmptyStateElement;
    };
    interface HTMLOzEventRowElement extends Components.OzEventRow, HTMLStencilElement {
    }
    var HTMLOzEventRowElement: {
        prototype: HTMLOzEventRowElement;
        new (): HTMLOzEventRowElement;
    };
    interface HTMLOzHeaderElement extends Components.OzHeader, HTMLStencilElement {
    }
    var HTMLOzHeaderElement: {
        prototype: HTMLOzHeaderElement;
        new (): HTMLOzHeaderElement;
    };
    interface HTMLOzIconElement extends Components.OzIcon, HTMLStencilElement {
    }
    var HTMLOzIconElement: {
        prototype: HTMLOzIconElement;
        new (): HTMLOzIconElement;
    };
    interface HTMLOzInputElementEventMap {
        "ozInput": string;
        "ozChange": string;
    }
    interface HTMLOzInputElement extends Components.OzInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOzInputElementEventMap>(type: K, listener: (this: HTMLOzInputElement, ev: OzInputCustomEvent<HTMLOzInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOzInputElementEventMap>(type: K, listener: (this: HTMLOzInputElement, ev: OzInputCustomEvent<HTMLOzInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOzInputElement: {
        prototype: HTMLOzInputElement;
        new (): HTMLOzInputElement;
    };
    interface HTMLOzKpiElement extends Components.OzKpi, HTMLStencilElement {
    }
    var HTMLOzKpiElement: {
        prototype: HTMLOzKpiElement;
        new (): HTMLOzKpiElement;
    };
    interface HTMLOzLineChartElement extends Components.OzLineChart, HTMLStencilElement {
    }
    var HTMLOzLineChartElement: {
        prototype: HTMLOzLineChartElement;
        new (): HTMLOzLineChartElement;
    };
    interface HTMLOzProductTableElement extends Components.OzProductTable, HTMLStencilElement {
    }
    var HTMLOzProductTableElement: {
        prototype: HTMLOzProductTableElement;
        new (): HTMLOzProductTableElement;
    };
    interface HTMLOzSidebarElement extends Components.OzSidebar, HTMLStencilElement {
    }
    var HTMLOzSidebarElement: {
        prototype: HTMLOzSidebarElement;
        new (): HTMLOzSidebarElement;
    };
    interface HTMLOzSparklineElement extends Components.OzSparkline, HTMLStencilElement {
    }
    var HTMLOzSparklineElement: {
        prototype: HTMLOzSparklineElement;
        new (): HTMLOzSparklineElement;
    };
    interface HTMLOzSwatchElement extends Components.OzSwatch, HTMLStencilElement {
    }
    var HTMLOzSwatchElement: {
        prototype: HTMLOzSwatchElement;
        new (): HTMLOzSwatchElement;
    };
    interface HTMLOzTagElement extends Components.OzTag, HTMLStencilElement {
    }
    var HTMLOzTagElement: {
        prototype: HTMLOzTagElement;
        new (): HTMLOzTagElement;
    };
    interface HTMLElementTagNameMap {
        "oz-avatar": HTMLOzAvatarElement;
        "oz-button": HTMLOzButtonElement;
        "oz-card": HTMLOzCardElement;
        "oz-empty-state": HTMLOzEmptyStateElement;
        "oz-event-row": HTMLOzEventRowElement;
        "oz-header": HTMLOzHeaderElement;
        "oz-icon": HTMLOzIconElement;
        "oz-input": HTMLOzInputElement;
        "oz-kpi": HTMLOzKpiElement;
        "oz-line-chart": HTMLOzLineChartElement;
        "oz-product-table": HTMLOzProductTableElement;
        "oz-sidebar": HTMLOzSidebarElement;
        "oz-sparkline": HTMLOzSparklineElement;
        "oz-swatch": HTMLOzSwatchElement;
        "oz-tag": HTMLOzTagElement;
    }
}
declare namespace LocalJSX {
    interface OzAvatar {
        /**
          * @default ''
         */
        "name"?: string;
        /**
          * @default 32
         */
        "size"?: number;
        /**
          * @default 'forest'
         */
        "tone"?: OzAvatarTone;
    }
    interface OzButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default 'md'
         */
        "size"?: OzButtonSize;
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * @default 'primary'
         */
        "variant"?: OzButtonVariant;
    }
    interface OzCard {
        /**
          * @default 'solid'
         */
        "border"?: OzCardBorder;
        /**
          * @default false
         */
        "elevated"?: boolean;
        "heading"?: string;
        /**
          * @default false
         */
        "interactive"?: boolean;
        /**
          * @default 'md'
         */
        "padding"?: OzCardPadding;
        "subheading"?: string;
        /**
          * @default 'default'
         */
        "tone"?: OzCardTone;
    }
    interface OzEmptyState {
        "body"?: string;
        /**
          * @default ''
         */
        "heading"?: string;
        /**
          * @default 'doc'
         */
        "icon"?: OzIconName;
    }
    interface OzEventRow {
        /**
          * @default ''
         */
        "amount"?: string;
        /**
          * @default ''
         */
        "dateDay"?: string;
        /**
          * @default ''
         */
        "dateMonth"?: string;
        /**
          * @default ''
         */
        "kind"?: string;
        /**
          * @default ''
         */
        "product"?: string;
        /**
          * @default 'forest'
         */
        "tone"?: OzTagTone;
    }
    interface OzHeader {
        /**
          * @default 'Tableau de bord'
         */
        "heading"?: string;
        /**
          * @default 3
         */
        "notificationCount"?: number;
        /**
          * @default 'Rechercher un ISIN, produit, client…'
         */
        "searchPlaceholder"?: string;
    }
    interface OzIcon {
        /**
          * @default 'currentColor'
         */
        "color"?: string;
        /**
          * @default 'dashboard'
         */
        "name"?: OzIconName1;
        /**
          * @default 16
         */
        "size"?: number;
        /**
          * @default 1.6
         */
        "strokeWidth"?: number;
    }
    interface OzInput {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "error"?: boolean;
        "hint"?: string;
        "label"?: string;
        "onOzChange"?: (event: OzInputCustomEvent<string>) => void;
        "onOzInput"?: (event: OzInputCustomEvent<string>) => void;
        "placeholder"?: string;
        /**
          * @default 'md'
         */
        "size"?: OzInputSize;
        /**
          * @default 'text'
         */
        "type"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface OzKpi {
        "delta"?: string;
        /**
          * @default 'success'
         */
        "deltaTone"?: OzTagTone;
        /**
          * @default ''
         */
        "label"?: string;
        "sub"?: string;
        "unit"?: string;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface OzLineChart {
        /**
          * @default 220
         */
        "h"?: number;
        /**
          * @default []
         */
        "series"?: OzSeries[] | string;
        /**
          * @default 560
         */
        "w"?: number;
        /**
          * @default []
         */
        "yLabels"?: string[] | string;
    }
    interface OzProductTable {
        /**
          * @default false
         */
        "compact"?: boolean;
        /**
          * @default DEFAULT_ROWS
         */
        "rows"?: OzProductRow[] | string;
    }
    interface OzSidebar {
        /**
          * @default 'dashboard'
         */
        "active"?: string;
        /**
          * @default 'Cabinet Helios'
         */
        "org"?: string;
        /**
          * @default 'Marie Laurent'
         */
        "user"?: string;
    }
    interface OzSparkline {
        /**
          * @default 'var(--oz-forest)'
         */
        "color"?: string;
        /**
          * @default []
         */
        "data"?: number[] | string;
        /**
          * @default 36
         */
        "h"?: number;
        /**
          * @default 160
         */
        "w"?: number;
    }
    interface OzSwatch {
        /**
          * @default 'var(--oz-ink)'
         */
        "fg"?: string;
        /**
          * @default 84
         */
        "h"?: number;
        "label"?: string;
        /**
          * @default ''
         */
        "name"?: string;
        /**
          * @default ''
         */
        "value"?: string;
        /**
          * @default 132
         */
        "w"?: number;
    }
    interface OzTag {
        /**
          * @default 'neutral'
         */
        "tone"?: OzTagTone1;
        /**
          * @default 'soft'
         */
        "variant"?: OzTagVariant;
    }

    interface OzAvatarAttributes {
        "name": string;
        "size": number;
        "tone": OzAvatarTone;
    }
    interface OzButtonAttributes {
        "variant": OzButtonVariant;
        "size": OzButtonSize;
        "disabled": boolean;
        "type": 'button' | 'submit' | 'reset';
    }
    interface OzCardAttributes {
        "heading": string;
        "subheading": string;
        "padding": OzCardPadding;
        "tone": OzCardTone;
        "border": OzCardBorder;
        "interactive": boolean;
        "elevated": boolean;
    }
    interface OzEmptyStateAttributes {
        "icon": OzIconName;
        "heading": string;
        "body": string;
    }
    interface OzEventRowAttributes {
        "dateMonth": string;
        "dateDay": string;
        "kind": string;
        "product": string;
        "amount": string;
        "tone": OzTagTone;
    }
    interface OzHeaderAttributes {
        "heading": string;
        "searchPlaceholder": string;
        "notificationCount": number;
    }
    interface OzIconAttributes {
        "name": OzIconName;
        "size": number;
        "color": string;
        "strokeWidth": number;
    }
    interface OzInputAttributes {
        "label": string;
        "placeholder": string;
        "value": string;
        "hint": string;
        "error": boolean;
        "size": OzInputSize;
        "type": string;
        "disabled": boolean;
    }
    interface OzKpiAttributes {
        "label": string;
        "value": string;
        "unit": string;
        "delta": string;
        "deltaTone": OzTagTone;
        "sub": string;
    }
    interface OzLineChartAttributes {
        "series": OzSeries[] | string;
        "yLabels": string[] | string;
        "w": number;
        "h": number;
    }
    interface OzProductTableAttributes {
        "rows": OzProductRow[] | string;
        "compact": boolean;
    }
    interface OzSidebarAttributes {
        "active": string;
        "user": string;
        "org": string;
    }
    interface OzSparklineAttributes {
        "data": number[] | string;
        "w": number;
        "h": number;
        "color": string;
    }
    interface OzSwatchAttributes {
        "name": string;
        "value": string;
        "label": string;
        "fg": string;
        "w": number;
        "h": number;
    }
    interface OzTagAttributes {
        "tone": OzTagTone;
        "variant": OzTagVariant;
    }

    interface IntrinsicElements {
        "oz-avatar": Omit<OzAvatar, keyof OzAvatarAttributes> & { [K in keyof OzAvatar & keyof OzAvatarAttributes]?: OzAvatar[K] } & { [K in keyof OzAvatar & keyof OzAvatarAttributes as `attr:${K}`]?: OzAvatarAttributes[K] } & { [K in keyof OzAvatar & keyof OzAvatarAttributes as `prop:${K}`]?: OzAvatar[K] };
        "oz-button": Omit<OzButton, keyof OzButtonAttributes> & { [K in keyof OzButton & keyof OzButtonAttributes]?: OzButton[K] } & { [K in keyof OzButton & keyof OzButtonAttributes as `attr:${K}`]?: OzButtonAttributes[K] } & { [K in keyof OzButton & keyof OzButtonAttributes as `prop:${K}`]?: OzButton[K] };
        "oz-card": Omit<OzCard, keyof OzCardAttributes> & { [K in keyof OzCard & keyof OzCardAttributes]?: OzCard[K] } & { [K in keyof OzCard & keyof OzCardAttributes as `attr:${K}`]?: OzCardAttributes[K] } & { [K in keyof OzCard & keyof OzCardAttributes as `prop:${K}`]?: OzCard[K] };
        "oz-empty-state": Omit<OzEmptyState, keyof OzEmptyStateAttributes> & { [K in keyof OzEmptyState & keyof OzEmptyStateAttributes]?: OzEmptyState[K] } & { [K in keyof OzEmptyState & keyof OzEmptyStateAttributes as `attr:${K}`]?: OzEmptyStateAttributes[K] } & { [K in keyof OzEmptyState & keyof OzEmptyStateAttributes as `prop:${K}`]?: OzEmptyState[K] };
        "oz-event-row": Omit<OzEventRow, keyof OzEventRowAttributes> & { [K in keyof OzEventRow & keyof OzEventRowAttributes]?: OzEventRow[K] } & { [K in keyof OzEventRow & keyof OzEventRowAttributes as `attr:${K}`]?: OzEventRowAttributes[K] } & { [K in keyof OzEventRow & keyof OzEventRowAttributes as `prop:${K}`]?: OzEventRow[K] };
        "oz-header": Omit<OzHeader, keyof OzHeaderAttributes> & { [K in keyof OzHeader & keyof OzHeaderAttributes]?: OzHeader[K] } & { [K in keyof OzHeader & keyof OzHeaderAttributes as `attr:${K}`]?: OzHeaderAttributes[K] } & { [K in keyof OzHeader & keyof OzHeaderAttributes as `prop:${K}`]?: OzHeader[K] };
        "oz-icon": Omit<OzIcon, keyof OzIconAttributes> & { [K in keyof OzIcon & keyof OzIconAttributes]?: OzIcon[K] } & { [K in keyof OzIcon & keyof OzIconAttributes as `attr:${K}`]?: OzIconAttributes[K] } & { [K in keyof OzIcon & keyof OzIconAttributes as `prop:${K}`]?: OzIcon[K] };
        "oz-input": Omit<OzInput, keyof OzInputAttributes> & { [K in keyof OzInput & keyof OzInputAttributes]?: OzInput[K] } & { [K in keyof OzInput & keyof OzInputAttributes as `attr:${K}`]?: OzInputAttributes[K] } & { [K in keyof OzInput & keyof OzInputAttributes as `prop:${K}`]?: OzInput[K] };
        "oz-kpi": Omit<OzKpi, keyof OzKpiAttributes> & { [K in keyof OzKpi & keyof OzKpiAttributes]?: OzKpi[K] } & { [K in keyof OzKpi & keyof OzKpiAttributes as `attr:${K}`]?: OzKpiAttributes[K] } & { [K in keyof OzKpi & keyof OzKpiAttributes as `prop:${K}`]?: OzKpi[K] };
        "oz-line-chart": Omit<OzLineChart, keyof OzLineChartAttributes> & { [K in keyof OzLineChart & keyof OzLineChartAttributes]?: OzLineChart[K] } & { [K in keyof OzLineChart & keyof OzLineChartAttributes as `attr:${K}`]?: OzLineChartAttributes[K] } & { [K in keyof OzLineChart & keyof OzLineChartAttributes as `prop:${K}`]?: OzLineChart[K] };
        "oz-product-table": Omit<OzProductTable, keyof OzProductTableAttributes> & { [K in keyof OzProductTable & keyof OzProductTableAttributes]?: OzProductTable[K] } & { [K in keyof OzProductTable & keyof OzProductTableAttributes as `attr:${K}`]?: OzProductTableAttributes[K] } & { [K in keyof OzProductTable & keyof OzProductTableAttributes as `prop:${K}`]?: OzProductTable[K] };
        "oz-sidebar": Omit<OzSidebar, keyof OzSidebarAttributes> & { [K in keyof OzSidebar & keyof OzSidebarAttributes]?: OzSidebar[K] } & { [K in keyof OzSidebar & keyof OzSidebarAttributes as `attr:${K}`]?: OzSidebarAttributes[K] } & { [K in keyof OzSidebar & keyof OzSidebarAttributes as `prop:${K}`]?: OzSidebar[K] };
        "oz-sparkline": Omit<OzSparkline, keyof OzSparklineAttributes> & { [K in keyof OzSparkline & keyof OzSparklineAttributes]?: OzSparkline[K] } & { [K in keyof OzSparkline & keyof OzSparklineAttributes as `attr:${K}`]?: OzSparklineAttributes[K] } & { [K in keyof OzSparkline & keyof OzSparklineAttributes as `prop:${K}`]?: OzSparkline[K] };
        "oz-swatch": Omit<OzSwatch, keyof OzSwatchAttributes> & { [K in keyof OzSwatch & keyof OzSwatchAttributes]?: OzSwatch[K] } & { [K in keyof OzSwatch & keyof OzSwatchAttributes as `attr:${K}`]?: OzSwatchAttributes[K] } & { [K in keyof OzSwatch & keyof OzSwatchAttributes as `prop:${K}`]?: OzSwatch[K] };
        "oz-tag": Omit<OzTag, keyof OzTagAttributes> & { [K in keyof OzTag & keyof OzTagAttributes]?: OzTag[K] } & { [K in keyof OzTag & keyof OzTagAttributes as `attr:${K}`]?: OzTagAttributes[K] } & { [K in keyof OzTag & keyof OzTagAttributes as `prop:${K}`]?: OzTag[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "oz-avatar": LocalJSX.IntrinsicElements["oz-avatar"] & JSXBase.HTMLAttributes<HTMLOzAvatarElement>;
            "oz-button": LocalJSX.IntrinsicElements["oz-button"] & JSXBase.HTMLAttributes<HTMLOzButtonElement>;
            "oz-card": LocalJSX.IntrinsicElements["oz-card"] & JSXBase.HTMLAttributes<HTMLOzCardElement>;
            "oz-empty-state": LocalJSX.IntrinsicElements["oz-empty-state"] & JSXBase.HTMLAttributes<HTMLOzEmptyStateElement>;
            "oz-event-row": LocalJSX.IntrinsicElements["oz-event-row"] & JSXBase.HTMLAttributes<HTMLOzEventRowElement>;
            "oz-header": LocalJSX.IntrinsicElements["oz-header"] & JSXBase.HTMLAttributes<HTMLOzHeaderElement>;
            "oz-icon": LocalJSX.IntrinsicElements["oz-icon"] & JSXBase.HTMLAttributes<HTMLOzIconElement>;
            "oz-input": LocalJSX.IntrinsicElements["oz-input"] & JSXBase.HTMLAttributes<HTMLOzInputElement>;
            "oz-kpi": LocalJSX.IntrinsicElements["oz-kpi"] & JSXBase.HTMLAttributes<HTMLOzKpiElement>;
            "oz-line-chart": LocalJSX.IntrinsicElements["oz-line-chart"] & JSXBase.HTMLAttributes<HTMLOzLineChartElement>;
            "oz-product-table": LocalJSX.IntrinsicElements["oz-product-table"] & JSXBase.HTMLAttributes<HTMLOzProductTableElement>;
            "oz-sidebar": LocalJSX.IntrinsicElements["oz-sidebar"] & JSXBase.HTMLAttributes<HTMLOzSidebarElement>;
            "oz-sparkline": LocalJSX.IntrinsicElements["oz-sparkline"] & JSXBase.HTMLAttributes<HTMLOzSparklineElement>;
            "oz-swatch": LocalJSX.IntrinsicElements["oz-swatch"] & JSXBase.HTMLAttributes<HTMLOzSwatchElement>;
            "oz-tag": LocalJSX.IntrinsicElements["oz-tag"] & JSXBase.HTMLAttributes<HTMLOzTagElement>;
        }
    }
}
